/**
 * Every user-facing string in the admin surface.
 *
 * PRD §5 Localisation asks for "a string layer ready for regional languages":
 * screens read from this object rather than embedding literals, so adding a
 * locale later means adding a sibling object and a lookup, not touching JSX.
 * Values that vary at runtime are functions returning the finished sentence,
 * because word order changes between languages.
 */

export const strings = {
  common: {
    add: 'Add',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    confirm: 'Confirm',
    edit: 'Edit',
    view: 'View',
    back: 'Back',
    export: 'Export',
    exportCsv: 'Export CSV',
    exportPdf: 'Export PDF',
    search: 'Search',
    filters: 'Filters',
    clearFilters: 'Clear filters',
    apply: 'Apply',
    all: 'All',
    loading: 'Loading...',
    somethingWentWrong: 'Something went wrong. Please try again.',
    offlineBanner: 'Showing saved data. Reconnect to refresh.',
    page: (page: number, total: number) => `Page ${page} of ${total}`,
    showingCount: (shown: number, total: number) => `Showing ${shown} of ${total}`,
    selectedCount: (count: number) => `${count} selected`,
  },

  dashboard: {
    title: 'Network overview',
    greeting: (name: string) => `Signed in as ${name}`,
    logout: 'Log out',
    tiles: {
      totalShops: 'Total shops',
      shopsSplit: (active: number, suspended: number) =>
        `${active} active · ${suspended} suspended`,
      ordersToday: 'Orders received today',
      pendingCutoff: 'Pending against cut-off',
      todaysValue: 'Today’s order value',
      networkOutstanding: 'Network outstanding',
      collectionsToday: 'Collections today',
    },
    cutoff: {
      title: 'Cut-off',
      countdownLabel: (time: string) => `Cut-off at ${time} IST`,
      remaining: (duration: string) => `${duration} remaining`,
      passed: 'Cut-off has passed. Orders are frozen.',
      submitted: (submitted: number, expected: number) =>
        `${submitted} of ${expected} shops submitted`,
      noOrder: (count: number) => `${count} marked "No order placed"`,
    },
    production: {
      title: 'Tomorrow’s production',
      kicker: 'Production requirement',
      subtitle: (date: string) => `For delivery on ${date}`,
      frozen: 'Frozen at cut-off',
      provisional: 'Provisional until cut-off',
      exportForKitchen: 'Export for kitchen',
      empty: 'No orders submitted for tomorrow yet.',
      viewFullPlan: 'View full production plan',
      moreItems: (count: number) => `+${count} more items`,
      notGenerated:
        "Tomorrow's production plan has not been generated yet. It is created from submitted orders once the cut-off passes.",
    },
    charts: {
      trendTitle: 'Order value trend',
      topProductsTitle: 'Top products by quantity',
      empty: 'No data for this range.',
      /**
       * Distinct from `empty`: "no data" and "we cannot ask for this data" look
       * identical on a blank chart but mean opposite things to whoever reads it.
       */
      unavailable:
        'Daily order-value trend is not available from the server yet.',
    },
    recentOrders: 'Recent orders',
    quickActions: 'Quick actions',
    actionOrders: 'All orders',
    actionShops: 'All shops',
    actionPayments: 'Payments queue',
    actionReports: 'Reports',
  },

  shops: {
    title: 'All shops',
    add: 'Add shop',
    searchPlaceholder: 'Search name, code or owner',
    statusLabel: 'Status',
    regionLabel: 'Region',
    sortLabel: 'Sort by',
    ageingToggle: 'Ageing view',
    ageingTitle: 'Outstanding by age',
    ageingBucket: (label: string) => `${label} days`,
    ageingShops: (count: number) => `${count} shops`,
    creditUtilisation: (percent: string) => `Credit used ${percent}`,
    outstanding: 'Outstanding',
    paidToDate: 'Paid to date',
    todaysOrder: 'Today’s order',
    noOrderToday: 'No order placed',
    empty: 'No shops match these filters.',
    suspend: 'Suspend',
    reactivate: 'Reactivate',
    deactivate: 'Deactivate',
    suspendTitle: 'Suspend this shop?',
    suspendMessage: (name: string) =>
      `${name} will keep access to its history but will not be able to place orders. This action is recorded in the audit trail.`,
    deactivateTitle: 'Deactivate this shop?',
    deactivateMessage: (name: string) =>
      `${name} will lose access to the app entirely. Existing orders and ledger entries are retained. This action is recorded in the audit trail.`,
    reactivateTitle: 'Reactivate this shop?',
    reactivateMessage: (name: string) => `${name} will be able to place orders again.`,
    statusChanged: 'Shop status updated.',
  },

  shopDetails: {
    title: 'Shop profile',
    createTitle: 'Add new shop',
    editTitle: 'Edit shop',
    sectionProfile: 'Profile',
    sectionCredit: 'Credit management',
    sectionMonthly: 'Monthly summary',
    sectionOrders: 'Order history',
    sectionLedger: 'Ledger',
    sectionPayments: 'Payments received',
    sectionAudit: 'Audit trail',
    tabs: {
      overview: 'Overview',
      orders: 'Orders',
      ledger: 'Ledger',
      payments: 'Payments',
    },
    franchiseOwner: 'Franchise owner',
    contactNumber: 'Contact number',
    taxId: 'GSTIN / Tax ID',
    moreDetails: 'More details',
    hideDetails: 'Hide details',
    statusToggle: 'Shop status',
    creditUsedCaption: (used: string, limit: string) => `${used} of ${limit} limit`,
    creditUtilisationCaption: (percent: string) => `${percent} of the limit is in use`,
    creditHealthy: 'Credit in good health',
    creditWatch: 'Approaching the credit limit',
    creditBreached: 'Credit limit exhausted',
    ordersThisMonth: 'Orders this month',
    totalOrderValue: 'Total order value',
    paymentsReceived: 'Payments received',
    adjustCreditLimit: 'Adjust credit limit',
    adjustCreditTitle: 'Adjust credit limit',
    adjustCreditHint: 'The new limit applies to the shop’s next order immediately.',
    orderValue: 'Order value',
    orderLines: (lines: number, units: string) =>
      `${lines} ${lines === 1 ? 'line' : 'lines'} · ${units} units`,
    shortSupply: 'Short supply',
    ordersInRange: (count: number) => `${count} ${count === 1 ? 'order' : 'orders'}`,
    ledgerBilled: 'Billed',
    ledgerReceived: 'Received',
    ledgerClosing: 'Closing balance',
    balanceAfter: (amount: string) => `Bal ${amount}`,
    noPayments: 'No payments or credit notes in this range.',
    ledgerTypes: {
      order: 'Order',
      invoice: 'Invoice',
      payment: 'Payment',
      credit_note: 'Credit note',
      adjustment: 'Adjustment',
    },
    deactivateShop: 'Deactivate shop',
    creditLimit: 'Credit limit',
    creditUsed: 'Credit used',
    creditAvailable: 'Available credit',
    priceList: 'Price list',
    cutoffOverride: 'Cut-off override',
    cutoffGlobal: 'Uses the global cut-off',
    adjustment: 'Add credit note / adjustment',
    adjustmentTitle: 'Manual adjustment',
    adjustmentHint:
      'Positive amounts increase what the shop owes; negative amounts issue a credit.',
    runningBalance: 'Balance',
    noLedger: 'No ledger entries in this range.',
    noOrders: 'This shop has not placed any orders yet.',
    noAudit: 'No administrative actions recorded yet.',
    inviteSent: 'Invite sent. The owner completes their profile on first login.',
    created: 'Shop created.',
    updated: 'Shop updated.',
    adjustmentPosted: 'Adjustment posted to the ledger.',
    fields: {
      name: 'Shop name',
      code: 'Shop code',
      ownerName: 'Owner name',
      ownerPhone: 'Owner phone',
      ownerEmail: 'Owner email',
      address: 'Address',
      gstin: 'GSTIN',
      region: 'Region',
      creditLimit: 'Credit limit',
      priceList: 'Price list',
      amount: 'Amount',
      reference: 'Reference',
      description: 'Description',
    },
    errors: {
      required: 'This field is required.',
      phone: 'Enter a 10-digit mobile number.',
      email: 'Enter a valid email address.',
      gstin: 'Enter a valid 15-character GSTIN.',
      creditLimit: 'Enter a credit limit of zero or more.',
      amount: 'Enter a non-zero amount.',
    },
  },

  orders: {
    title: 'Orders',
    subtitle: 'Franchise order management',
    searchPlaceholder: 'Search by shop, order ID or item...',
    selectRange: 'Select range',
    filtersTitle: 'Filter orders',
    dateRangeLabel: 'Date range',
    filterSummary: (count: number) =>
      `${count} ${count === 1 ? 'filter' : 'filters'} applied`,
    itemsAndValue: 'Items & value',
    itemsAndValueCount: (items: number, value: string) =>
      `${items} ${items === 1 ? 'item' : 'items'} · ${value}`,
    statusAgo: (status: string, ago: string) => `${status} ${ago}`,
    quickAccept: 'Accept order',
    selectionHint: 'Long-press an order to select several at once.',
    statusLabel: 'Status',
    shopLabel: 'Shop',
    dateFieldLabel: 'Date',
    orderDate: 'Order date',
    deliveryDate: 'Delivery date',
    pendingCutoff: 'Pending cut-off',
    empty: 'No orders match these filters.',
    /**
     * The list is genuinely unfiltered by date here, so saying so beats
     * showing rows that look filtered and are not.
     */
    dateFilterUnsupported:
      'Showing all dates. Filtering orders by a date range is not supported by the server yet.',
    emptyPendingCutoff: 'Every shop has submitted for this cut-off.',
    bulkAccept: 'Accept selected',
    bulkProduction: 'Move to production',
    bulkCancel: 'Cancel selected',
    bulkTitle: (action: string, count: number) => `${action} ${count} orders?`,
    bulkMessage: (action: string, count: number) =>
      `This applies "${action}" to ${count} orders and records each change in the audit trail.`,
    bulkDone: (count: number) => `${count} orders updated.`,
    bulkFailed: 'Bulk update failed. No orders were changed.',
    exportStarted: (format: string) => `Export queued as ${format.toUpperCase()}.`,
    timelineTitle: 'Status timeline',
  },

  orderDetails: {
    title: 'Order detail',
    subtitle: (shop: string, orderId: string) => `${shop} · ${orderId}`,
    progress: 'Order progress',
    itemsCount: (count: number) => `Order items (${count})`,
    itemNote: (note: string) => `Note: ${note}`,
    deliveringNote: (quantity: string) => `Delivering ${quantity}`,
    sectionShop: 'Shop',
    captureShortSupply: 'Capture short supply',
    startProduction: 'Start production',
    items: 'Items',
    ordered: 'Ordered',
    delivered: 'Delivered',
    unitPrice: 'Unit price',
    lineTotal: 'Total',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Order total',
    shortSupply: 'Short supply',
    shortSupplyNote: 'Delivered quantity is below the ordered quantity.',
    contact: 'Shop contact',
    submittedAt: 'Submitted',
    notSubmitted: 'Not submitted',
    cutoffAt: 'Cut-off',
    afterCutoff: 'Submitted after cut-off',
    reopened: 'Reopened by admin',
    reopenAction: 'Reopen after cut-off',
    reopenTitle: 'Reopen this order?',
    reopenMessage:
      'The shop will be able to edit and resubmit this order. The reopen is recorded in the audit trail with your name and reason.',
    reopenReasonLabel: 'Reason',
    reopenReasonRequired: 'A reason is required to reopen an order.',
    reopenDone: 'Order reopened. The shop has been notified.',
    accept: 'Accept order',
    reject: 'Reject order',
    markDispatched: 'Mark dispatched',
    markDelivered: 'Mark delivered',
    generateInvoice: 'Generate invoice',
    cancel: 'Cancel order',
    printOrder: 'Print order',
    exportPdf: 'Export as PDF',
    viewInvoice: 'View invoice',
    deliveredTitle: 'Record delivery',
    deliveredMessage:
      'Enter the quantity actually delivered for each line. Anything below the ordered quantity is recorded as short supply.',
    confirmTransition: (label: string) => `${label}?`,
    transitionMessage: (label: string) =>
      `This moves the order to "${label}" and notifies the shop. The change is recorded in the audit trail.`,
    statusUpdated: 'Order status updated.',
    cancelTitle: 'Cancel this order?',
    cancelMessage:
      'The shop will be notified that the order was cancelled. This cannot be undone.',
  },

  shortSupply: {
    title: 'Short supply',
    subtitle: (orderId: string, shop: string) => `${orderId} · ${shop}`,
    intro:
      'Indicate quantities that cannot be fully fulfilled for tomorrow’s run. Shops will be automatically notified.',
    ordered: 'Ordered',
    delivering: 'Delivering',
    shortfall: 'Shortfall',
    reasonLabel: 'Reason for shortage',
    reasonPlaceholder: 'Select a reason',
    reasonRequired: 'Choose a reason for every short line.',
    reasons: {
      stock: 'Stock shortage',
      ingredient: 'Ingredient unavailable',
      production: 'Production delay',
      quality: 'Quality rejection',
      capacity: 'Kitchen capacity',
      other: 'Other',
    },
    summaryNone: 'Every line is being delivered in full.',
    summaryShort: (lines: number) =>
      `${lines} ${lines === 1 ? 'line' : 'lines'} short of the ordered quantity.`,
    confirm: 'Confirm short supply',
    confirmTitle: 'Confirm short supply?',
    confirmMessage: (lines: number, shop: string) =>
      `${lines} ${lines === 1 ? 'line' : 'lines'} will be sent short and ${shop} will be notified. The change is recorded in the audit trail.`,
    recorded: 'Short supply recorded. The shop has been notified.',
    decrease: 'Decrease quantity',
    increase: 'Increase quantity',
  },

  productionPlan: {
    title: 'Production requirement',
    subtitle: 'Consolidated baking schedule',
    searchPlaceholder: 'Search bakery items...',
    tomorrow: 'Tomorrow',
    today: 'Today',
    columnProduct: 'Bakery product',
    columnShops: 'Shops',
    columnQty: 'Qty req.',
    shops: (count: number) => `${count} ${count === 1 ? 'shop' : 'shops'}`,
    exportPlan: 'Export production plan (PDF/CSV)',
    empty: 'Nothing to bake for this date yet.',
    emptyFiltered: 'No items match this search or section.',
    totals: (items: number, quantity: string) => `${items} items · ${quantity} total`,
    categories: {
      all: 'All items',
      cakes: 'Cakes',
      pastries: 'Pastries',
      savoury: 'Savoury',
      dryItems: 'Dry items',
    },
  },

  productionDetail: {
    title: 'Production detail',
    subtitle: 'Order breakdown by shop',
    totalRequired: 'Total qty required',
    orderingShops: 'Ordering shops',
    orderingShopsValue: (ordered: number, total: number) => `${ordered} / ${total}`,
    demandTrend: 'Demand trend (last 7 days)',
    shopBreakdown: 'Shop breakdown',
    noNote: 'No special notes',
    empty: 'No shop has ordered this item for this date.',
    unitSuffix: (quantity: string, unit: string) => `${quantity} ${unit}`,
  },

  placeholder: {
    comingSoon: 'Coming soon',
    body: 'This screen is part of the next admin batch.',
  },
} as const;

export default strings;
