import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

export default function PaymentsScreen() {
  const [method, setMethod] = useState('UPI');
  return (
    <View style={styles.container}><Text style={styles.eyebrow}>CHECKOUT</Text><Text style={styles.title}>Payment</Text><Text style={styles.subtitle}>Choose how you&apos;d like to settle this order.</Text><View style={styles.amount}><Text style={styles.amountLabel}>PAYABLE NOW</Text><Text style={styles.amountValue}>Rs 2,480</Text></View>{['UPI', 'Card', 'NetBanking'].map(item => <Pressable key={item} style={[styles.option, method === item && styles.selected]} onPress={() => setMethod(item)}><View style={[styles.radio, method === item && styles.radioSelected]} /><Text style={styles.optionText}>{item}</Text><Text style={styles.arrow}>›</Text></Pressable>)}<Pressable style={styles.button} onPress={() => {}}><Text style={styles.buttonText}>Continue with {method}</Text></Pressable><Text style={styles.note}>Razorpay checkout will be connected here.</Text></View>
  );
}
const styles = StyleSheet.create({ container: { backgroundColor: '#F8F5F0', flex: 1, padding: 22, paddingTop: 30 }, eyebrow: { color: '#A85B3F', fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, title: { color: '#2B2521', fontSize: 32, fontWeight: '800', marginTop: 5 }, subtitle: { color: '#7C716A', fontSize: 14, marginTop: 5 }, amount: { backgroundColor: '#2B2521', borderRadius: 17, marginVertical: 25, padding: 20 }, amountLabel: { color: '#E9DCCF', fontSize: 11, fontWeight: '700' }, amountValue: { color: '#FFF9F3', fontSize: 30, fontWeight: '800', marginTop: 5 }, option: { alignItems: 'center', backgroundColor: '#FFFDFC', borderColor: '#FFFDFC', borderRadius: 13, borderWidth: 1, flexDirection: 'row', marginBottom: 10, padding: 17 }, selected: { borderColor: '#A85B3F' }, radio: { borderColor: '#BEB2A8', borderRadius: 9, borderWidth: 2, height: 18, width: 18 }, radioSelected: { backgroundColor: '#A85B3F', borderColor: '#A85B3F' }, optionText: { color: '#3D332E', flex: 1, fontSize: 15, fontWeight: '700', marginLeft: 12 }, arrow: { color: '#A85B3F', fontSize: 23 }, button: { alignItems: 'center', backgroundColor: '#A85B3F', borderRadius: 12, marginTop: 16, padding: 16 }, buttonText: { color: '#FFF9F3', fontSize: 15, fontWeight: '800' }, note: { color: '#9A8D84', fontSize: 12, marginTop: 13, textAlign: 'center' }, });
